### ISSUE TITLE
bad footnote

### ISSUE THREAD

**Issue by TQueV** [TQueV/covid-19#53]
Die Fußnoten sind nicht korrekt gesetzt: Die Nummerierung wird zweimal angezeigt und die Fußnote erscheint nicht, wie im Original, als bubble, sondern im Text. Siehe: https://github.com/TQueV/covid-19/blob/master/pics/bad-footnote.png

**Comment by lenaschimmel** [comment]
Es fehlte ein Anführungszeichen in einem meta-tag, wodurch das css für die Fußnoten nicht geladen wurde. Habs [hier](https://github.com/TQueV/covid-19/commit/43505da45056b13bc33548454fb05cc704f123f7) gefixt.
