### ISSUE TITLE
translation pics

### ISSUE THREAD

**Issue by TQueV** [TQueV/covid-19#55]
Manche Bilder sind noch nicht korrigiert (siehe: https://github.com/TQueV/covid-19/blob/master/GERMAN_TRANSL_NOTES.md) und die Begriffe stimmen jetzt teilweise nicht mehr überein.

**Comment by herrhundt** [comment]
Habe masks.png korrigiert, hier tauchten Rechtschreibfehler auf.

**Comment by TQueV** [comment]
Cool, bin jetzt auch fertig mit dem Rest
