### ISSUE TITLE
R > 1?

### ISSUE THREAD

**Issue by Hartifially** [TQueV/covid-19#60]
Bei der Aufforderung zum Teilen soll es vermutlich R < 1 heißen, oder?

**Comment by herrhundt** [comment]
Ein bisschen doppeldeutig, in der Tat. Damit ist wohl die Reproduktionszahl der Weiterverbreitung des Artikels gemeint, nicht die des Virus ;)

**Comment by Hartifially** [comment]
🤦🏾‍♂️, danke!
