### ISSUE TITLE
thumbnail.png is English original in Twitter

### ISSUE THREAD

**Issue by TQueV** [TQueV/covid-19#61]
Beim Teilen auf Twitter wird das englische Original-Thumbnail (https://github.com/ncase/covid-19/blob/master/sharing/thumbnail.png) angezeigt, beim Teilen auf Facebook allerdings das deutsche (https://github.com/TQueV/covid-19/blob/master/sharing/thumbnail.png). Weiß wer woran das liegen könnte?

**Comment by lenaschimmel** [comment]
Aus dem Chat:

> @felixrindt: Vielleicht hat twitter das Thumbnail gecached, bevor wir es übersetzt haben?
> 
> @lenaschimmel : Kann sein. Man kann das mit https://cards-dev.twitter.com/validator testen, was ich eben getan habe. Ich vermute, dass dieses Testen implizit auch den Cache zurück setzt, zumindest wird da die deutsche Fassung angezeigt.
> Ich hab auch eben mal auf einem nicht-öffentlichen Twitter-Account einen Test-Tweet gemacht, da wird auch deutscher Text und deutsche Grafik angezeigt, also alles ok.

Ich denke, damit ist das behoben. @TQueV, kannst du bestätigen, dass das bei dir auch nicht mehr auftritt?

**Comment by herrhundt** [comment]
Funktioniert nun wie gewünscht, danke!
